on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        run: npm ci

      # Uncomment this step if you have a build process, otherwise skip it
      # - name: Build the app
      #   run: npm run build

      - name: Run Cypress tests
        run: npm test
